version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install dependencies
          command: make install
      - python/save-cache
      - run:
          name: Lint 
          command: make lint

workflows:
  main:
    jobs:
      - build-and-test
